#! /bin/sh

org_opts=$@
command=$1

base='$(git config nyt.base)'

apply()
{
    eval $(printf $@)
}
diff()
{
    for x in $1
    do 
	if [ "$(eval $(printf 'a=%s;for b in %s;do if [ "$a" = "$b" ]; then echo $a; break; fi; done' $x "$2"))" = "" ] ;then echo $x;fi
    done
}

shift
case ${command} in
  clear) git config --unset nyt.base ;;
  base) git config nyt.base $@ ;;
  list) eval git log --format=%H $base.. $@ | tail -r ;;
  diff) eval git diff $base $@;;
  rebase)
    eval git rebase -i $base $@
    git nyt clear;;
  fixup)
    eval "git reset --mixed $base; git add .; git commit -a $@"
    git nyt clear;;
  fixup-part)
    all=$(git nyt list)
    list=$(cat - | cut -f 1)
    eval git reset --hard $base
    for c in $list; do git cherry-pick $c; done
    git nyt fixup $@
    for c in $(diff "$all" "$list"); do git cherry-pick $c; done
   ;;
  bleis)
    all=$(git nyt list)
    eval git reset --hard $base

    for c in $all; do 
	files=$(git show --pretty=oneline --name-only $c | sed -ne '2,$p')
	difffiles=$(diff "$files" "$oldfiles")
	echo "amend:$difffiles"
	if [ "$difffiles" = "" ]
	then 
	    git reset --mixed $c
	    git add .
	    git commit --amend -m $(git log --pretty=%s -1 $c)
	else git cherry-pick $c
	fi
	oldfiles=$files
    done
    ;;
  *)
    git config nyt.base
    if [ "$?" = "1" ]; then
	git nyt base $(git log -1 --format=%H)
    fi
    
    git $org_opts
    ;;
esac

