#! /bin/sh

org_opts=$@
command=$1

base='$(git config nyt.base)'

shift
case ${command} in
  clear) git config --unset nyt.base ;;
  list) eval "git log --format=%H $base.. $@" ;;
  diff) eval "git diff $base $@";;
  rebase)
    eval "git rebase -i $base $@"
    git nyt clear;;
  fixup)
    eval "git reset --mixed $base; git add .; git commit -a $@"
    git nyt clear;;
  fixup-part)
    all=$(git nyt list)
    list=$(cat -)

    ;;
  *)
    git config nyt.base
    if [ "$?" = "1" ]; then
	git config nyt.base $(git log -1 --format=%H)
    fi

    git $org_opts
    ;;
esac

